library(dplyr)
library(reshape)
library(ggplot2)

# questions: How do browsers and mobile devices chance user behavior?
# About 1/7 of the actions do not have the uuid variable recorded. 
# We can check whether the distibutions of actions are power law distributed.


setwd("/Users/pantelispa/Desktop/Project-resources/Scrooge")
list.files()

theDataset <- read.csv(file = "data.csv", header = FALSE, sep = ",")
theDataset <- read.csv(file = "newData.csv", header = TRUE, sep = ",")


# Examine the table generated by a single user.

singleUser <- filter(theDataset,uuid == "104d0d7516ce00e1cd02bd2883ac8004")
singleUser <- filter(theDataset,uuid == "")
numberOfActions <- length(singleUser[,1])

# Count all the users and generate a data structure to store new variables. 

allUsers <- levels(theDataset$uuid)
nUsers <- 101
sessionStatistics <- matrix(rep(0,2*(nUsers - 1)),nrow = 2)

# Loop in the users and calculate different session related variables.


for (i in 2:nUsers){
    theUser <- filter(theDataset,uuid == allUsers[i])
    sessionStatistics[1,(i - 1)] <- length(theUser[,1])
    sessionStatistics[2,(i - 1)] <- theUser$ts[length(theUser[,1])] - theUser$ts[1]}


# tranform the data in a dataframe

sessionStatistics <- as.data.frame(t(sessionStatistics))
summary(sessionStatistics)

# use ggplot to produce simple graphs

qplot(sessionStatistics$V1, geom="histogram",binwidth = 2)
qplot(sessionStatistics$V2, geom="histogram")
